version: "3"
services:

 django: &django
  build:
   context: ./
  volumes:
   - shared_temp:/tmp
   - ./media/:/media
   - ./django_examples/:/app
   - ./django_modals/:/modals/django_modals
   - /var/run/docker.sock:/var/run/docker.sock
  command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8007"
  environment:
   - PYTHONPATH=/modals
  ports:
   - 8007:8007

 redis:
   image: redis:5.0.7-alpine

 celery:
   <<: *django
   image: modal_celeryworker
   command: celery -A django_examples worker -l info
   labels:
     - "none"
   ports:
    - 80

volumes:
  shared_temp: {}